---
title: "Hetero Analysis"
author: "Yicheng Shen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mosaic)
library(purrr)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
```


```{r}
res <- read.csv('res/res_binary.csv')   
res2 <- read.csv('res/htelogit_tau50.csv')   
res3 <- read.csv('res/ab_tau50.csv')   

modelname = rep("htelogit_tau50", nrow(res2))
col.group = rep("Bayesian", nrow(res2))
pch.group = rep("HTE model", nrow(res2))

res2 = cbind(res2[, 1:3], modelname, col.group, pch.group, res2[, 4:ncol(res2)])
res2$I.2 = NA


modelname = rep("ablogit_tau50", nrow(res3))
col.group = rep("Bayesian", nrow(res3))
pch.group = rep("HTE model", nrow(res3))

res3 = cbind(res3[, 1:3], modelname, col.group, pch.group, res3[, 4:ncol(res3)])
res3$I.2 = NA

res_all = rbind(res, res2, res3)
```


```{r}
result = res_all %>% 
  mutate(modelname = factor(modelname, levels = c("ivfe", "ivre", "ctevaguelogit","ctebeta", "htevaguelogit", "htelogit_tau50", "htebeta", "ablogit", "ablogit_tau50")))

n_distinct(result$MA.id)
nrow(result) # 9 model result per study

table((result %>% distinct(MA.id, .keep_all = TRUE))$event)
```


```{r}
result = result %>% 
  mutate(Significant_num = 1-as.numeric(0 >= low & 0 <= up)) %>% 
  mutate(Significant = ifelse(Significant_num == "1", "significant", "non-significant"))

result$Significant <- factor(result$Significant, levels = c("significant", "non-significant")) 

# result %>% ggplot() + geom_ribbon(aes(x = MA.id, ymin = low, ymax = up)) + facet_wrap(~modelname)
```


## analyze seperate outcome type

```{r}
result_com = result %>% filter(event %in% c("common"))
result_if = result %>% filter(event %in% c("infrequent"))
result_ra = result %>% filter(event %in% c("rare"))
result_vra = result %>% filter(event %in% c("very rare"))
```


# tau


```{r}
result_bayesian %>% 
  select(MA.id, modelname, tau, tauc, taua) %>% 
  filter(MA.id == 10) 

cor(
  result_bayesian[result_bayesian$modelname == "htelogit_tau50",]$tau,
  result_bayesian[result_bayesian$modelname == "ablogit_tau50",]$taua
  )

cor(
  result_bayesian[result_bayesian$modelname == "htelogit_tau50",]$tau,
  result_bayesian[result_bayesian$modelname == "ablogit_tau50",]$tauc
  )


ggplot() + geom_point( aes(
                       result_bayesian[result_bayesian$modelname == "htelogit_tau50",]$tau, 
                       result_bayesian[result_bayesian$modelname == "ablogit_tau50",]$taua))

ggplot() + geom_point( aes(
                       result_bayesian[result_bayesian$modelname == "htelogit_tau50",]$tau, 
                       result_bayesian[result_bayesian$modelname == "ablogit_tau50",]$tauc))


cor(
  result_bayesian[result_bayesian$modelname == "htebeta",]$taua,
  result_bayesian[result_bayesian$modelname == "ablogit_tau50",]$taua
  )

cor(
  result_bayesian[result_bayesian$modelname == "htebeta",]$tauc,
  result_bayesian[result_bayesian$modelname == "ablogit_tau50",]$tauc
  )


ggplot() + geom_point( aes(
                       result_bayesian[result_bayesian$modelname == "htebeta",]$taua, 
                       result_bayesian[result_bayesian$modelname == "ablogit_tau50",]$taua))

ggplot() + geom_point( aes(
                       result_bayesian[result_bayesian$modelname == "htebeta",]$tauc, 
                       result_bayesian[result_bayesian$modelname == "ablogit_tau50",]$tauc))

```




```{r}
missing.MA.id = (result %>% filter(modelname == "htebeta") %>% filter(is.na(est)))$MA.id
result_narm = result %>% filter(! MA.id %in% missing.MA.id)
```



```{r, fig.width=12}
result_bayesian = result_narm %>% filter(col.group == "Bayesian")
result_bayesian %>% filter(MA.id == 10) %>% select(modelname, col.group, pch.group, waic)

result_bayesian %>%
  group_by(MA.id) %>%
  mutate(order = rank(waic, ties.method = "min")) %>% 
  filter(MA.id == 10) %>% select(modelname, waic, order)


result_bayesian %>%
  group_by(MA.id) %>%
  mutate(order = rank(waic, ties.method = "min")) %>% 
  ungroup %>% 
  group_by(modelname, order) %>%
  summarize(count = n()) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = modelname, y = percentage, fill = as.factor(order))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Percentage of Ranking Orders by Model",
       x = "Model",
       y = "Percentage") +
  scale_fill_manual(values = c("1" = "blue", "2" = "red", "3" = "green", "4" = "purple", "5" = "orange", "6" = "pink", "7" = "brown"))


result_bayesian %>%
  group_by(MA.id) %>%
  mutate(order = rank(waic, ties.method = "min")) %>% 
  ggplot(aes(factor(order), fill = modelname)) +
  geom_bar(position = "fill", color = "Black") +
  scale_y_continuous(labels = scales::percent) + labs(x = "", y = "proportion")
```


```{r, fig.width=12}
result_bayesian_rare = result_narm %>% filter(col.group == "Bayesian", event != "common")
result_bayesian_rare %>% filter(MA.id == 10) %>% select(modelname, col.group, pch.group, waic)


result_bayesian_rare %>%
  group_by(MA.id) %>%
  mutate(order = rank(waic, ties.method = "min")) %>% 
  ungroup %>% 
  group_by(modelname, order) %>%
  summarize(count = n()) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = modelname, y = percentage, fill = as.factor(order))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Percentage of Ranking Orders by Model",
       x = "Model",
       y = "Percentage") +
  scale_fill_manual(values = c("1" = "blue", "2" = "red", "3" = "green", "4" = "purple", "5" = "orange", "6" = "pink", "7" = "brown"))


result_bayesian_rare %>%
  group_by(MA.id) %>%
  mutate(order = rank(waic, ties.method = "min")) %>% 
  ggplot(aes(factor(order), fill = modelname)) +
  geom_bar(position = "fill", color = "Black") +
  scale_y_continuous(labels = scales::percent) + labs(x = "", y = "proportion")
```


